# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

#trigger:
#- main

#pool:
#  vmImage: ubuntu-latest
#pool: sh_pool

#steps:
#- script: echo Hello, world!
#  displayName: 'Run a one-line script'

#- script: |
#    echo Add other tasks to build, test, and deploy your project.
#    echo See https://aka.ms/yaml
#  displayName: 'Run a multi-line script'




trigger:
  branches:
    include:
      - main

pr: none

variables:
  FlutterChannel: 'stable'
  FlutterVersion: 'latest'

jobs:
  - job: Testing_of_SonarQube_with_Flutter
    pool: sh_pool

    steps:
      #- task: FlutterInstall@0
      #  displayName: Setup Flutter
      #  inputs:
      #    channel: '$(FlutterChannel)'
      #    version: '$(FlutterVersion)'

      - task: SonarQubePrepare@4
        inputs:
          SonarQube: 'SonarQube Service Connection'
          scannerMode: 'CLI'
          configMode: 'manual'
          cliProjectName: 'rr_web_front'
          cliProjectKey: 'rr_$(Build.Repository.Name)'
          cliSources: '.'
          extraProperties: |
            # Additional properties that will be passed to the scanner, 
            # Put one key=value per line, example:
            # sonar.exclusions=**/*.bin
            sonar.projectName=rr_web_front
            sonar.projectKey=rr_web_front
            sonar.login=5811d224cbb2d2621a8bd357a67a781342746cfd
            sonar.host.url=http://deepflamessonqrqubedns.eastus.azurecontainer.io:9000
            sonar.javascript.lcov.reportPaths=./coverage/lcov.info
            sonar.dart.analysis.useExistingOptions=false

      - task: CmdLine@2
        inputs:
          script: |
            echo Hack SonarQube

            export SONARQUBE_SCANNER_PARAMS=$(echo $SONARQUBE_SCANNER_PARAMS | sed -E 's/"sonar.branch.name":"main",//g')

            printenv

      - task: CmdLine@2
        displayName: Run install
        inputs:
          script: 'flutter pub get'

      - task: CmdLine@2
        displayName: Run test
        inputs:
          script: 'flutter test --machine > tests.output'

      - task: CmdLine@2
        displayName: Run coverage
        inputs:
          script: 'flutter test --coverage'

      - task: SonarQubeAnalyze@4
        displayName: Run analyze

      - task: SonarQubePublish@4
        displayName: Run publish
        inputs:
          pollingTimeoutSec: '300'